resources:
- github.com/partiallyordered/mojaloop-kustomize/base/nginx-ingress-controller?ref=ee2ffcc2588dcefda74ed6b4f2e47a7388f67f4e
- github.com/partiallyordered/mojaloop-kustomize/base/mojaloop/central?ref=49fb1e37d817a757ff7d172c29b84f31bfb20cc3
- manifests/portal-frontend
- github.com/partiallyordered/voodoo-doll/kubernetes?ref=9cf23085f7ebd6dbaa4a95a21e8d63e15f35502b
- github.com/mojaloop/wso2is-populate/integration_test/manifests/wso2is?ref=v2.0.4
- github.com/mojaloop/wso2is-populate/integration_test/manifests/wso2is-populate?ref=v2.0.4

configMapGenerator:
- name: oauth-app-credentials
  literals: &oauth_creds
  - AUTH_SERVER_CLIENTKEY=fv0xZxstzo2_qVcqMRFpLI43xm8mZZ
  - AUTH_SERVER_CLIENTSECRET=CJvf1mQxQdLqWLYuNvAicRd6iBMQo5
- name: wso2is-populate
  literals:
  - WSO2_HOST=https://wso2is:9443
- name: portal-backend
  behavior: merge
  literals: *oauth_creds

patches:
- patch: |-
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: wso2is-populate
    spec:
      # Sometimes WSO2 is painfully slow to start.
      backoffLimit: 100
      template:
        spec:
          containers:
          - name: job
            image: ghcr.io/mojaloop/wso2is-populate:v2.0.4
            envFrom:
            - configMapRef:
                name: oauth-app-credentials
            - configMapRef:
                name: wso2is-populate
