resources:
- github.com/partiallyordered/mojaloop-kustomize/base/nginx-ingress-controller?ref=f15e5d949ca1f62a63feecbd44534e98b953a386
- github.com/partiallyordered/mojaloop-kustomize/base/mojaloop/central?ref=f15e5d949ca1f62a63feecbd44534e98b953a386
- github.com/partiallyordered/voodoo-doll/kubernetes?ref=067c1ea2016c40e2b07119acbfdee484f1bccdb8
- github.com/mojaloop/wso2is-populate/integration_test/manifests/wso2is?ref=v2.0.4
- github.com/mojaloop/wso2is-populate/integration_test/manifests/wso2is-populate?ref=v2.0.4
- ing.yaml

configMapGenerator:
- name: oauth-app-credentials
  literals: &oauth_creds
  - AUTH_SERVER_CLIENTKEY=fv0xZxstzo2_qVcqMRFpLI43xm8mZZ
  - AUTH_SERVER_CLIENTSECRET=CJvf1mQxQdLqWLYuNvAicRd6iBMQo5
- name: wso2is-populate
  literals:
  - WSO2_HOST=https://wso2is:9443
- name: portal-backend
  behavior: merge
  literals: *oauth_creds
- name: portal-backend
  behavior: merge
  literals:
  # Testcafe doesn't handle secure cookies well. For our integration tests, we make the cookie
  # insecure. This is because:
  # 1. we expect to remove auth functionality from the portal backend in the near future and hand
  #    it off to a third-party tool
  # 2. with (1) in mind, this meant we didn't need to spend time investigating the precise clause
  #    in the cookie that causes the problem
  # 3. it's not important for our tests to be secure
  #
  # Of course, the trade-off is that our tests are slightly less representative of a real
  # deployment, but we accept that because of (1).
  - INSECURE_COOKIE=true
- name: wso2is-populate-users
  files:
  - users.json=./users.json

patches:
- patch: |-
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: wso2is-populate
    spec:
      # Sometimes WSO2 is painfully slow to start.
      backoffLimit: 100
      template:
        spec:
          containers:
          - name: job
            image: ghcr.io/mojaloop/wso2is-populate:v2.0.4
            envFrom:
            - configMapRef:
                name: oauth-app-credentials
            - configMapRef:
                name: wso2is-populate
            volumeMounts:
            - name: user-config
              mountPath: /src/imports/users.json
              subPath: users.json
          volumes:
          - name: user-config
            configMap:
              name: wso2is-populate-users
