{{- if .Values.ingress.enabled }}
{{- $fullName := include "finance-portal-v2-ui.fullname" . }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "finance-portal-v2-ui.labels" . | indent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
    - hosts:
      - {{ .Values.ingress.externalHostname | quote }}
      secretName: {{ .Values.ingress.tls.secretName }}
{{- end }}
  rules:
    - host: {{ .Values.ingress.externalHostname }}
      http:
        paths:
          - path: /()(.*)
            backend:
              serviceName: {{ include "finance-portal-v2-ui.fullname" . }}
              servicePort: http
          - path: /api/login(/|$)(.*)
            backend:
              serviceName: {{ .Values.ingress.loginService.name }}
              servicePort: {{ .Values.ingress.loginService.portName }}
          - path: /api/settlement(/|$)(.*)
            backend:
              serviceName: {{ .Values.ingress.settlementService.name }}
              servicePort: {{ .Values.ingress.settlementService.portName }}
          - path: /api/portal-backend(/|$)(.*)
            backend:
              serviceName: {{ .Values.ingress.portalBackend.name }}
              servicePort: {{ .Values.ingress.portalBackend.portName }}

{{- end }}
