name: Validate chart

on: [pull_request, push]

jobs:
  manifest_validation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/8e4fe32876ca15e3d5eb3ecd3ca0b224417f5f17.tar.gz
    - name: Install dependencies
      run: nix-env -if integration_test/chart/default.nix
    - name: Run manifest validation
      run: helm template testname helm/finance-portal-settlements | kubeconform -strict -kubernetes-version 1.17.9

  smoke_test_deploy:
    needs: manifest_validation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/8e4fe32876ca15e3d5eb3ecd3ca0b224417f5f17.tar.gz
    - name: Install dependencies
      run: nix-env -if integration_test/chart/default.nix
    # Cluster setup
    - name: Start cluster
      run: |-
        # --k3s-server-arg args according to
        # https://k3d.io/faq/faq/#solved-nodes-fail-to-start-or-get-stuck-in-notready-state-with-log-nf_conntrack_max-permission-denied
        k3d cluster create \
          --k3s-server-arg "--kube-proxy-arg=conntrack-max-per-core=0" \
          --k3s-agent-arg "--kube-proxy-arg=conntrack-max-per-core=0" \
          --kubeconfig-update-default \
          --kubeconfig-switch-context \
          --image=rancher/k3s:v1.17.9-k3s1 \
          int-test
    - name: Deploy
      run: helm install int-test ./helm/finance-portal-settlements
    - name: Setup tmate session
      if: ${{ failure() }}
      uses: mxschmitt/action-tmate@v3
      timeout-minutes: 10
